# Generated by Django 5.1.2 on 2025-10-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nazwa kalendarza (np. 'Warsaw Westies Dance')", max_length=200)),
                ('calendar_id', models.CharField(help_text="ID kalendarza Google (np. 'warsawwestiesdance@gmail.com')", max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Czy kalendarz jest aktywny')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kalendarz',
                'verbose_name_plural': 'Kalendarze',
                'ordering': ['name'],
            },
        ),
    ]
