# Generated by Django 5.1.2 on 2025-10-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'ordering': ['name'], 'verbose_name': 'Calendar', 'verbose_name_plural': 'Calendars'},
        ),
        migrations.AlterField(
            model_name='calendar',
            name='calendar_id',
            field=models.CharField(help_text="Google Calendar ID (e.g. 'warsawwestiesdance@gmail.com')", max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the calendar is active'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='name',
            field=models.CharField(help_text="Calendar name (e.g. 'Warsaw Westies Dance')", max_length=200),
        ),
    ]
