version: '3.8'

services:
  backend-dev:
    build: ./backend
    container_name: westnfound_backend_dev
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-dev-secret-key-change-in-production}
      - DEBUG=True
      - DJANGO_ADMIN_URL=${DJANGO_ADMIN_URL:-admin}
    restart: unless-stopped
    profiles:
      - dev

  backend-prod:
    build: ./backend
    container_name: westnfound_backend_prod
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn westnfound.wsgi:application --bind 0.0.0.0:8000 --workers 4"
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-dev-secret-key-change-in-production}
      - DEBUG=False
      - DJANGO_ADMIN_URL=${DJANGO_ADMIN_URL:-admin}
    restart: unless-stopped
    profiles:
      - prod

  frontend-dev:
    image: nginx:alpine
    container_name: westnfound_frontend_dev
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "${FRONTEND_BIND_IPV4:-0.0.0.0}:${FRONTEND_PORT:-80}:80"
      - "[${FRONTEND_BIND_IPV6:-::}]:${FRONTEND_PORT:-80}:80"
    depends_on:
      - backend-dev
    restart: unless-stopped
    profiles:
      - dev

  frontend-prod:
    image: nginx:alpine
    container_name: westnfound_frontend_prod
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/usr/share/nginx/static:ro
    ports:
      - "${FRONTEND_BIND_IPV4:-0.0.0.0}:${FRONTEND_PORT:-80}:80"
      - "[${FRONTEND_BIND_IPV6:-::}]:${FRONTEND_PORT:-80}:80"
    depends_on:
      - backend-prod
    restart: unless-stopped
    profiles:
      - prod

volumes:
  static_volume:
